### ISSUE TITLE
too much CPU and memory,panic after hours

### ISSUE THREAD

**Issue by mzw-g** [sundy-li/burrowx#17]
(1)panic:
      panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x77252a]

goroutine 568 [running]:
github.com/sundy-li/burrowx/monitor.(*KafkaClient).offsetFetchImport(0xc000208000)
	G:/gowork/src/github.com/sundy-li/burrowx/monitor/client.go:245 +0x1ea
github.com/sundy-li/burrowx/monitor.(*KafkaClient).getOffsets(0xc000208000, 0x0, 0x0)
	G:/gowork/src/github.com/sundy-li/burrowx/monitor/client.go:224 +0x7f7
github.com/sundy-li/burrowx/monitor.(*KafkaClient).Start.func1(0xc000208000)
	G:/gowork/src/github.com/sundy-li/burrowx/monitor/client.go:144 +0x60
created by github.com/sundy-li/burrowx/monitor.(*KafkaClient).Start
	G:/gowork/src/github.com/sundy-li/burrowx/monitor/client.go:142 +0x9a

(2)cpu and memory
    cpu  from 5% up to 90%
    memory from %0.5 up to 30%
    and keep growing

I just monitored 6 topics, max partition is 40.

**Comment by mzw-g** [comment]
I had fixed it
#18
