### ISSUE TITLE
Describe configuration parameters

### ISSUE THREAD

**Issue by asyd** [sundy-li/burrowx#7]
Hi, 

can you describe what is expected for `general.ClientProfile` and `kafka.ClientProfile`?

I have the following configuration
```json
{
  "general": {
    "logconfig": "config/logging.xml",
    "pidfile": "burrowx.pid",
    "clientId": "burrowx-lagchecker",
    "groupBlacklist": "^(console-consumer-|python-kafka-consumer-|KafkaWebView).*$",

    "topicFilter" : "*",

    "clientProfile" : {
        "xxx" : {
          "clientId" : "burrowx",
          "tls": "false",
          "tlsNoverify": "",
          "tlsCertfilepath": "",
          "tlsKeyfilepath": "",
          "tlsCafilepath": ""
        }
    }
  },
  "zookeeper": {
    "hosts": "xx.xx.137.102:2181,xx.xx.137.103:2181,xx.xx.137.104:21821",
    "timeout": 6,
    "lock-path": "/burrow/notifier"
  },
  "kafka": {
    "local": {
      "brokers": "xx.xx.137.112:9092,xx.xx.137.109:9092,xx.xx.137.113:9092,xx.xx.137.111:9092,xx.xx.137.110:9092",
      "zookeepers": "xx.xx.137.102:2181,xx.xx.137.103:2181,xx.xx.137.104:21821",
      "offsetsTopic": "__consumer_offsets",
      "ClientProfile": "xxx"
    }
  },
  "influxdb": {
    "enable": true,
    "hosts": "http://xx.xx.137.69:8086",
    "db": "telegraf",
    "username": "",
    "pwd": ""
  }
}

```

But burrowx failed to start:

```
2018/06/13 14:20:31 burrowx started,using server config:burrowx.json, logfile cfg:config/logging.xml
2018/06/13 14:20:31 You could press [Ctrl+c] to stop burrowx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7579af]

goroutine 1 [running]:
github.com/sundy-li/burrowx/monitor.NewKafkaClient(0xc4200f9860, 0xc420024fc3, 0x5, 0xc42000e188, 0x0, 0x1)
        /root/go/src/github.com/sundy-li/burrowx/monitor/client.go:55 +0xcf
github.com/sundy-li/burrowx/monitor.NewFetcher(0xc4200f9860, 0x29, 0x0, 0x0)
        /root/go/src/github.com/sundy-li/burrowx/monitor/fetcher.go:18 +0x162
main.main()
        /root/go/src/github.com/sundy-li/burrowx/main.go:30 +0x139

```

And regarding line 55 of `client.go` I suspect it's related to `clientProfile`.

Thanks

**Comment by sundy-li** [comment]
Hi, the `kafka.ClientProfile` is the key to `client.ClientProfile`, you could set the `kafka.ClientProfile` to empty string to ignore it.

**Comment by asyd** [comment]
If both are empty, here the error I have:

```
2018/07/03 14:42:10 burrowx started,using server config:burrowx.json, logfile cfg:config/logging.xml
2018/07/03 14:42:10 You could press [Ctrl+c] to stop burrowx
panic: regexp: Compile(`*`): error parsing regexp: missing argument to repetition operator: `*`

goroutine 1 [running]:
regexp.MustCompile(0xc420024e68, 0x1, 0xa)
        /root/tools/go/src/regexp/regexp.go:240 +0x171
github.com/sundy-li/burrowx/monitor.NewKafkaClient(0xc4200f9860, 0xc420024fb0, 0x5, 0xc42000e188, 0x0, 0x1)
        /root/go/src/github.com/sundy-li/burrowx/monitor/client.go:126 +0x661
github.com/sundy-li/burrowx/monitor.NewFetcher(0xc4200f9860, 0x29, 0x0, 0x0)
        /root/go/src/github.com/sundy-li/burrowx/monitor/fetcher.go:18 +0x162
main.main()
        /root/go/src/github.com/sundy-li/burrowx/main.go:30 +0x13
```

**Comment by sundy-li** [comment]
Sorry, the doc is out date , I add some comments to the [server.json.sample](https://github.com/sundy-li/burrowx/blob/master/config/server.json.sample)
